---
- hosts: testing
  sudo: yes
  gather_facts: yes

  tasks:

  - name: Installing Fail2Ban
    apt: pkg=fail2ban state=latest update_cache=yes

  - name: Installing logwatch
    apt: pkg=logwatch state=latest update_cache=yes
