---
- hosts: testing

  tasks:

  - name: Install Required Packages
    yum: name={{ item }} state=latest
    with_items:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2

  - name: Add Docker Repo
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docer-ce.repo

  - name: Enable Docker Edge Repo
    ini_file:
      dest: /etc/yum.repos.d/docer-ce.repo
      section: 'docker-ce-edge'
      option: enabled
      value: 0

  - name: Install Docker CE
    yum: 
      name: docker-ce
      state: latest

  - name: Start & Enable Docker Service
    systemd:
      name: docker
      state: started
      enabled: yes
      masked: no

  - name: Add user "user" to docker group
    user:
      name: user
      groups: docker
      append: yes
