---
### Install default packages
- name: Install default packages
  yum: name={{ item }} state=latest
  with_items:
    - epel-release
    - htop
    - vim
    - bash-completion
    - tmux
    - git
    - nmap
    - tcpdump
    - net-tools
    - bind-utils